language: java
sudo: required
# necessary in order to avoid killing of certain tests because of memory consumption (not sure why adding `sudo: required` changes this)

# specifying other dists doesn't make sense because `trusty` doesn't have `oraclejdk8` (fails due to `Sorry, but JDK '[oraclejdk8]' is not known.`) which is the only supported JDK currently. Testing on Mac OSX doesn't make too much sense since it will run the same `maven` based build routine.

jdk:
- oraclejdk8
# `openjdk8` not available

env:
- MAVEN_OPTS="-Xmx6g -Xms2g"

before_install:
# We need Maven < 3.2 because it's enforced in `javaocr`
- wget http://mirrors.ae-online.de/apache/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
- tar xf apache-maven-3.1.1-bin.tar.gz
- export M2_HOME=$PWD/apache-maven-3.1.1
- export PATH=$M2_HOME/bin:$PATH
- sudo apt-get update
- sudo apt-get install --yes genisoimage
# necessary for `sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle`
- sudo apt-get install --yes fakeroot

- sudo apt-get install libaio1 libaio-dev
    # avoid `libaio.so.1: cannot open shared object file: No such file or directory`
- wget https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.17-linux-glibc2.5-x86_64.tar.gz
- tar xf mysql-5.7.17-linux-glibc2.5-x86_64.tar.gz && mv mysql-5.7.17-linux-glibc2.5-x86_64 $HOME/mysql-5.7.17
# for integration tests
- git clone https://github.com/krichter722/maven-parent && cd maven-parent && mvn install && cd ..

install: /bin/true

script:
- sudo service postgresql stop
- sudo service mysql stop
    # avoid conflict which instance started by integration tests (`mysql-server` and `mysqld` are unrecognized services)
- sudo netstat -tupln
    # debug conflicting port for integration tests
- env MAVEN_OPTS="-Xmx6g -Xms2g" mvn install --update-snapshots -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version && mvn test verify --batch-mode
