language: java
sudo: required
# necessary in order to avoid killing of certain tests because of memory consumption (not sure why adding `sudo: required` changes this)

jdk:
- oraclejdk8
# `openjdk8` not available

env:
- MAVEN_OPTS="-Xmx6g -Xms2g"

before_install:
# We need Maven < 3.2 because it's enforced in `javaocr`
- wget http://mirrors.ae-online.de/apache/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz
- tar xf apache-maven-3.1.1-bin.tar.gz
- export M2_HOME=$PWD/apache-maven-3.1.1
- export PATH=$M2_HOME/bin:$PATH
- sudo apt-get update
- sudo apt-get install --yes genisoimage
# necessary for `sh.tak.appbundler:appbundle-maven-plugin:1.2.0:bundle`

install: /bin/true

script:
- env MAVEN_OPTS="-Xmx6g -Xms2g" mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- env MAVEN_OPTS="-Xmx6g -Xms2g" mvn test -B
