/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package richtercloud.orientdb.document.scanner.gui;

import javax.swing.JScrollPane;

/**
 *
 * @author richter
 */
public class DocumentTab extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    private String title;

    /**
     * Creates new form DocumentTab
     */
    public DocumentTab() {
        initComponents();
    }
    
    public DocumentTab(String title) {
        this();
        this.title = title;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        documentForm = new richtercloud.orientdb.document.scanner.gui.DocumentForm();
        imageScrollPane = new javax.swing.JScrollPane();

        splitPane.setDividerLocation(350);
        splitPane.setRightComponent(documentForm);
        splitPane.setLeftComponent(imageScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splitPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public JScrollPane getImageScrollPane() {
        return imageScrollPane;
    }

    protected void setImageScrollPane(JScrollPane imageScrollPane) {
        this.imageScrollPane = imageScrollPane;
    }

    public String getTitle() {
        return title;
    }

    protected void setTitle(String title) {
        this.title = title;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private richtercloud.orientdb.document.scanner.gui.DocumentForm documentForm;
    private javax.swing.JScrollPane imageScrollPane;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables
}
